export const publicHeroSlides = [
  {
    key: 'overview',
    title: '上海高校专业发展公开展示平台',
    description: '集中查看院校概况、专业表现与公开就业数据。',
    actionLabel: '查看数据',
    actionType: 'scroll-overview',
    image: '/assets/上海4.jpg',
    imagePosition: 'center 38%',
  },
  {
    key: 'compare',
    title: '院校对比与公开监测',
    description: '结合地图与对比图表，查看上海高校专业结构与就业表现。',
    actionLabel: '查看院校对比',
    actionType: 'navigate-compare',
    image: '/assets/上海5.jpg',
    imagePosition: 'center 30%',
  },
  {
    key: 'major',
    title: '面向社会公众的高校信息展示',
    description: '以正式、清晰、可阅读的方式呈现公开数据。',
    actionLabel: '查看总览',
    actionType: 'scroll-gallery',
    image: '/assets/上海6.jpg',
    imagePosition: 'center 36%',
  },
]

export const publicUniversityCards = [
  {
    key: 'shu',
    name: '上海大学',
    subtitle: '综合性高校，专业门类覆盖较全，制造与信息类岗位吸纳较稳定。',
    image: '/assets/上海大学2.jpg',
    employmentRate: '95.2%',
    avgSalary: '8620 元',
    hotIndustry: '智能制造、软件服务',
    samples: '1,286 条',
  },
  {
    key: 'fudan',
    name: '复旦大学',
    subtitle: '学科实力突出，科研与高端服务业岗位占比较高。',
    image: '/assets/复旦大学.jpg',
    employmentRate: '96.4%',
    avgSalary: '9840 元',
    hotIndustry: '金融服务、生物医药',
    samples: '1,104 条',
  },
  {
    key: 'tongji',
    name: '同济大学',
    subtitle: '工程类专业优势明显，建筑、汽车与数字化岗位需求持续活跃。',
    image: '/assets/同济大学.png',
    employmentRate: '95.8%',
    avgSalary: '9310 元',
    hotIndustry: '智能建造、汽车工程',
    samples: '1,032 条',
  },
  {
    key: 'ecnu',
    name: '华东师范大学',
    subtitle: '教育、数据与人文社科融合发展，就业去向结构较均衡。',
    image: '/assets/华东师范大学.jpg',
    employmentRate: '94.6%',
    avgSalary: '8150 元',
    hotIndustry: '教育服务、数据分析',
    samples: '968 条',
  },
]
