# -*- coding: utf-8 -*-
from __future__ import annotations

SCHOOL_PROFILES = [
    {
        "school_id": "SHU001",
        "school_name": "上海交通大学",
        "school_type": "综合研究型 / 双一流",
        "city": "上海市",
        "district": "闵行区",
        "discipline_strength_tags": ["船舶海洋", "机械工程", "能源动力", "电子信息", "临床医学", "人工智能", "金融科技"],
        "ace_majors": ["船舶与海洋工程", "机械工程", "能源与动力工程", "电子科学与技术", "临床医学", "口腔医学", "生物医学工程", "计算机科学与技术", "自动化", "信息工程", "经济学", "工商管理"],
        "industry_affinity": ["智能制造", "医疗健康", "电子信息", "人工智能", "船舶海洋", "科研研发", "金融服务"],
        "major_count": 76,
        "first_class_major_count": 42,
        "salary_level_factor": 1.24,
        "employment_stability_factor": 1.12,
        "research_factor": 1.28,
        "application_factor": 1.05,
        "policy_response_factor": 1.18,
    },
    {
        "school_id": "SHU002",
        "school_name": "复旦大学",
        "school_type": "综合研究型 / 双一流",
        "city": "上海市",
        "district": "杨浦区",
        "discipline_strength_tags": ["经济金融", "法政社会", "新闻传播", "生命医学", "微电子", "数据分析"],
        "ace_majors": ["哲学", "经济学", "法学", "国际政治", "社会学", "汉语言文学", "新闻学", "历史学", "数学与应用数学", "物理学", "化学", "生物科学", "微电子科学与工程", "电子信息科学与技术", "计算机科学与技术", "基础医学", "临床医学", "预防医学", "药学", "会计学"],
        "industry_affinity": ["金融服务", "公共服务", "新闻传媒", "生物医药", "医疗健康", "集成电路", "数据分析", "咨询研究"],
        "major_count": 82,
        "first_class_major_count": 45,
        "salary_level_factor": 1.22,
        "employment_stability_factor": 1.10,
        "research_factor": 1.30,
        "application_factor": 1.00,
        "policy_response_factor": 1.16,
    },
    {
        "school_id": "SHU003",
        "school_name": "同济大学",
        "school_type": "工科优势综合研究型 / 双一流",
        "city": "上海市",
        "district": "杨浦区",
        "discipline_strength_tags": ["土木建筑", "城市规划", "交通运输", "环境治理", "汽车工程", "工业设计"],
        "ace_majors": ["土木工程", "建筑学", "城乡规划", "风景园林", "交通工程", "环境工程", "给排水科学与工程", "测绘工程", "地质工程", "机械设计制造及其自动化", "车辆工程", "软件工程", "计算机科学与技术", "工业设计", "德语"],
        "industry_affinity": ["建筑设计", "城市规划", "土木工程", "交通运输", "环境治理", "新能源汽车", "工业设计", "工程管理"],
        "major_count": 74,
        "first_class_major_count": 39,
        "salary_level_factor": 1.16,
        "employment_stability_factor": 1.11,
        "research_factor": 1.16,
        "application_factor": 1.16,
        "policy_response_factor": 1.12,
    },
    {
        "school_id": "SHU004",
        "school_name": "华东师范大学",
        "school_type": "师范综合研究型 / 双一流",
        "city": "上海市",
        "district": "普陀区",
        "discipline_strength_tags": ["教师教育", "心理学", "教育技术", "统计数据", "基础教育研究"],
        "ace_majors": ["教育学", "学前教育", "特殊教育", "教育技术学", "心理学", "应用心理学", "汉语言文学", "英语", "历史学", "地理科学", "统计学", "软件工程", "数据科学与大数据技术", "微电子科学与工程"],
        "industry_affinity": ["教育培训", "基础教育", "心理服务", "教育技术", "数据科学", "公共服务", "数字教育产品"],
        "major_count": 70,
        "first_class_major_count": 31,
        "salary_level_factor": 1.02,
        "employment_stability_factor": 1.18,
        "research_factor": 1.12,
        "application_factor": 1.04,
        "policy_response_factor": 1.10,
    },
    {
        "school_id": "SHU005",
        "school_name": "华东理工大学",
        "school_type": "理工行业特色 / 双一流",
        "city": "上海市",
        "district": "徐汇区",
        "discipline_strength_tags": ["化工制药", "材料工程", "环境治理", "过程装备", "新能源材料"],
        "ace_majors": ["化学工程与工艺", "过程装备与控制工程", "应用化学", "制药工程", "生物工程", "高分子材料与工程", "环境工程", "自动化", "资源循环科学与工程", "新能源材料与器件", "信息管理与信息系统"],
        "industry_affinity": ["化工制药", "材料工程", "环境治理", "新能源材料", "过程装备", "智能制造"],
        "major_count": 63,
        "first_class_major_count": 27,
        "salary_level_factor": 1.08,
        "employment_stability_factor": 1.09,
        "research_factor": 1.08,
        "application_factor": 1.14,
        "policy_response_factor": 1.14,
    },
    {
        "school_id": "SHU006",
        "school_name": "上海财经大学",
        "school_type": "财经特色 / 双一流",
        "city": "上海市",
        "district": "杨浦区",
        "discipline_strength_tags": ["金融会计", "财政税务", "风险控制", "金融科技", "统计分析"],
        "ace_majors": ["会计学", "财务管理", "金融学", "经济学", "财政学", "国际经济与贸易", "工商管理", "统计学", "电子商务", "法学", "保险学", "市场营销", "劳动与社会保障"],
        "industry_affinity": ["金融服务", "会计审计", "税务咨询", "投资研究", "风险控制", "保险精算", "数据风控", "金融科技"],
        "major_count": 44,
        "first_class_major_count": 21,
        "salary_level_factor": 1.18,
        "employment_stability_factor": 1.05,
        "research_factor": 1.00,
        "application_factor": 1.12,
        "policy_response_factor": 1.09,
    },
    {
        "school_id": "SHU007",
        "school_name": "上海大学",
        "school_type": "综合应用研究型 / 双一流",
        "city": "上海市",
        "district": "宝山区",
        "discipline_strength_tags": ["数字媒体", "智能制造", "材料工程", "通信工程", "文化传播", "社会治理", "档案信息化", "城市建设", "产品设计"],
        "ace_majors": ["社会学", "汉语言文学", "广播电视学", "历史学", "数学与应用数学", "理论与应用力学", "机械设计制造及其自动化", "金属材料工程", "通信工程", "数字媒体技术", "土木工程", "工商管理", "档案学", "美术学", "环境设计"],
        "industry_affinity": ["数字媒体", "智能制造", "材料工程", "通信工程", "文化传播", "社会治理", "档案信息化", "城市建设", "产品设计"],
        "major_count": 86,
        "first_class_major_count": 32,
        "salary_level_factor": 1.07,
        "employment_stability_factor": 1.08,
        "research_factor": 1.04,
        "application_factor": 1.13,
        "policy_response_factor": 1.13,
    },
    {
        "school_id": "SHU008",
        "school_name": "东华大学",
        "school_type": "纺织服装与材料特色 / 双一流",
        "city": "上海市",
        "district": "长宁区",
        "discipline_strength_tags": ["纺织新材料", "服装设计", "时尚产业", "供应链管理", "绿色制造"],
        "ace_majors": ["纺织工程", "服装设计与工程", "服装与服饰设计", "高分子材料与工程", "复合材料与工程", "轻化工程", "环境工程", "机械工程", "自动化", "信息管理与信息系统", "电子商务", "工业设计"],
        "industry_affinity": ["纺织服装", "时尚设计", "供应链管理", "绿色制造", "材料研发", "品牌电商"],
        "major_count": 56,
        "first_class_major_count": 24,
        "salary_level_factor": 1.00,
        "employment_stability_factor": 1.06,
        "research_factor": 0.98,
        "application_factor": 1.17,
        "policy_response_factor": 1.08,
    },
    {
        "school_id": "SHU009",
        "school_name": "上海外国语大学",
        "school_type": "外语与国际传播特色 / 双一流",
        "city": "上海市",
        "district": "虹口区",
        "discipline_strength_tags": ["外语翻译", "国际传播", "跨境商务", "涉外法务", "语言技术"],
        "ace_majors": ["英语", "俄语", "阿拉伯语", "德语", "法语", "西班牙语", "翻译", "商务英语", "新闻学", "国际政治", "国际经济与贸易", "外交学", "汉语国际教育"],
        "industry_affinity": ["国际传播", "翻译", "本地化运营", "跨境电商", "外事服务", "国际组织", "涉外法务", "语言技术", "国际商务"],
        "major_count": 42,
        "first_class_major_count": 20,
        "salary_level_factor": 1.01,
        "employment_stability_factor": 1.03,
        "research_factor": 0.96,
        "application_factor": 1.14,
        "policy_response_factor": 1.05,
    },
    {
        "school_id": "SHU010",
        "school_name": "上海理工大学",
        "school_type": "应用理工特色",
        "city": "上海市",
        "district": "杨浦区",
        "discipline_strength_tags": ["先进制造", "光电仪器", "能源动力", "医疗器械", "出版传媒", "食品工程"],
        "ace_majors": ["编辑出版学", "机械设计制造及其自动化", "测控技术与仪器", "能源与动力工程", "光电信息科学与工程", "环境工程", "生物医学工程", "管理科学", "计算机科学与技术", "食品科学与工程", "医学影像技术", "产品设计"],
        "industry_affinity": ["先进制造", "光电仪器", "能源动力", "医疗器械", "出版传媒", "食品工程", "产品设计", "环境工程"],
        "major_count": 61,
        "first_class_major_count": 19,
        "salary_level_factor": 1.03,
        "employment_stability_factor": 1.07,
        "research_factor": 0.94,
        "application_factor": 1.18,
        "policy_response_factor": 1.09,
    },
]
